# Generated by Django 4.2.7 on 2026-09-11 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_useractivitylog_activity_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useractivitylog",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("register", "Register"),
                    ("login", "Login"),
                    ("logout", "Logout"),
                    ("profile_update", "Profile Update"),
                    ("password_change", "Password Change"),
                    ("password_reset", "Password Reset"),
                    ("email_change", "Email Change"),
                    ("email_verified", "Email Verified"),
                    ("admin_update", "Admin Update"),
                ],
                max_length=20,
            ),
        ),
    ]
