# Generated by Django 4.2.7 on 2026-09-11 02:05

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_useractivitylog_activity_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profile_pics/",
                validators=[accounts.validators.validate_profile_picture_size],
            ),
        ),
    ]
